### PR TITLE
Pay to relay

### PR DESCRIPTION
**Pull request by thesimplekid**
Still need to clean some things up, but the start of a pay to relay implementation with LNbits.

### CODE REVIEW

**Comment by dajuguan** [comment]
is there a doc or a nip?

**Comment by scsibug** [comment]
Well, this is an awesome thing to see come in!

**Comment by thesimplekid** [comment]
[NIP-111](https://github.com/nostr-protocol/nips/pull/163) is related as it can be used to define costs.  I will certainly add some docs.

**Comment by thesimplekid** [comment]
Hi @scsibug, 
sorry this got a little bigger then I originally thought should have checked with you early.  But wanted to give an update and get your take on a few things. This adds pay to relay support with LNBits used to generate invoices and accept payments. A user can add there pubkey and get an invoice via dms or via webpage "/join". 
Note: the dms get persisted to the DB but there is a bug where the broadcast is delayed. 

I wanted to get your take on dependencies, I think it would be good to have tor support as many run their nodes behind tor but i believe achieving this would either either require reqwest as it supports socks5 proxy or i think #30 could work or don't support tor? Ive also added [nostr-rust](https://github.com/rust-nostr/nostr) for DMs and [qrcode-rust](https://github.com/mikedilger/qrcode-rust).  

I could also see a case for the pay-to-relay being removed from here and run separately using the gRPC api you've added? Do you think that would be better? 

Thanks

**Comment by scsibug** [comment]
I think pay-to-relay is getting enough traction that it makes sense to include in the main code.

I don't have any experience with Tor, but if it isn't simple to support, I'd rather just not have the extra dependencies.  I don't have any way of testing or maintaining it in any case.

**Comment by thesimplekid** [comment]
I think the best way to support tor and .onion address right now is run tor separately and connect via SOCKS5 proxy using reqwest which isn't ideal. Maybe can be revisited when [Arti](https://gitlab.torproject.org/tpo/core/arti/-/tree/main/crates/arti-client) is more mature.

**Comment by thesimplekid** [comment]
> I'd rather just not have the extra dependencies. I don't have any way of testing or maintaining it in any case.

I've removed reqwest and used hyper to make lnbits api calls.  It does require that lnbits have a valid certificate and not a self signed certificate.

**Comment by scsibug** [comment]
Thanks for all this work, will review over the next couple of days.

**Comment by scsibug** [comment]
I've merged this, and will spend some time regression testing and then setting a lnbits environment for testing.

Thanks again for the great work on this, if you have any pointers for how you tested, i'd love to duplicate that.

**Comment by thesimplekid** [comment]
Awesome! thanks for merging.  I mainly tested by manually going through the sign up process with many accounts, ensuring users that have not paid events are not persisted and paid users events are. 

When the invoice is created a webhook is set (<relay_url>/lnbits) that lnbits calls when the invoice gets paid but if invoice is paid but the webhook fails, the next time the user posts an event there status will be checked and they will be admitted.  This can tested by incorrectly setting the `relay_url` in the config.  

https://legend.lnbits.com/ is useful for lnbits testing environment as the lnbits instance needs a valid non-self signed certificate and that can be a bit of a pain depending on how your own lighting node is set up.

**Pull request closed without merging**
