### PR TITLE
Add postgres support

### PR DESCRIPTION
**Pull request by v0l**
Hi,

Main changes of this PR:
1. Abstract database calls to `NostrRepo` trait
2. Switch database calls to use fully async `sqlx` package
3. Re-implement sqlite db calls into `SqliteRepo`
4. Implement postgres db calls into `PostgresRepo`
5. Implement basic prometheus metrics collection on read/write operations

There are more things to do:
- [ ] Catch up on optimizations
- [ ] Complete pending `todo()` sections

Latest build is also deployed here: `wss://beta.nostr.v0l.io`

Metrics:
image

### CODE REVIEW

**Comment by v0l** [comment]
Too large, closing

**Comment by Giszmo** [comment]
Wait, you gave up on adding postgres? :(

**Comment by v0l** [comment]
> Wait, you gave up on adding postgres? :(

Nope it works great, i just had a bunch of other changes on this branach now and it doesnt make sense to merge them all in a single PR

**Comment by scsibug** [comment]
I've been out for a bit, but I'm looking forward to digging into this as well.

**Comment by 0xtrr** [comment]
@v0l what is the best way to migrate from the sqlite db to a postgres db?

**Comment by v0l** [comment]
@0xtrr I created a backup of the database as JSON-ND and just pushed it back into the relay when it was configured for postgres.

You could do it manually but i would not recommend that, better to let nostr-rs-relay run all its checks before inserting the data as normal.

How many events do you have?

**Comment by 0xtrr** [comment]
> I created a backup of the database as JSON-ND

@v0l How did you export the events? Did you write some custom script for it or is there any existing tools for doing this?

> How many events do you have?

I have 16.5 million events

**Pull request closed without merging**
