### PR TITLE
Concrete definition of all protocol message types

### PR DESCRIPTION
**Pull request by rajarshimaitra**
This ended up being a very large change set. There was no good way to do this incrementally, so I decided to just write it all.

It doesn't make sense to review this via diffs, instead the final code at the top commit should reviewed like reading new code.

Here's a summary of the refactor
 - All protocol level structs like `Event`, `Tag`, `ReqFilter` etc are defined with concrete types. They can serialize and deserialize themselves into protocol json format.
 - The recommended way to deserialize an `Event` is via `Event::from_str()`. The custom definition of `from_str()` for event ensures that received event data is valid by `format`, `datatype` and `signature`. This ensure we never deal with invalid event data in other parts of the code. 
 - Map structures used in `Event` and `ReqFilter` is removed, as they are not needed when we already know how to handle these data efficiently.
 -  Commands and Responses are defined with their own struct (serialization defined). There are three types of commands `Close`, `Event`, `Subscription`. And 2 responses `EventResp` and `NoticeResp`. Easy constructors added for them.
 - All the message structs are moved into one dedicated module `messages` to keep this part of the code self contained. It can be thought that the entire nostr protocol lives in `messages`. Any future update to protocol will only require update there.
 - Basic testing added for all the types.
 - Minor fixes in error module to use this_error more efficiently.
 - Auxiliary changes to other part of the code for above refactors.
 
 I hope this is a helpful change. I am already seeing many simplification possible in other parts of the code (main, db etc). The idea is again the old concept of "separation of concerns". The server or database should not have to worry about protocol adherence of the stuffs they are handling. If they get something without panic, that's correct data. And everything "protocol" is contained inside `message` module.
 
 I tried to cover all the basic testing. More test suggestions are welcome.

### CODE REVIEW

**Comment by scsibug** [comment]
First practical problem; event kinds other than 0,1,2 are not accepted.  I think the relay should accept any kind, even those it isn't aware of.  This should be an easier fix (adding a "OtherKind" as a catchall for the `EventKind` enum).

**Comment by scsibug** [comment]
Second problem; the event/pubkey tags need to be more flexible.  When used in Kind=3 events (contact list), they can hold 4 values (tagname, pubkey, relay, nickname).

Future kinds could redefine these to do other things.  I really think we need to be able to handle arbitrary future events that meet the structure in NIP-01 (which doesn't prevent e/p tags from having an arbitrary number of elements).

**Comment by scsibug** [comment]
I think I'm OK with the relay rejecting events that are clearly out-of-spec (say, kind=3 with a "p" tag whose 2nd element is not a 64-byte hex string).  However, I think we need to ensure that unknown/future event kinds are parseable without having to explicitly add support for them.

I think pretty much everything else in the patch looks great.

**Comment by rajarshimaitra** [comment]
Thanks for the look.

Yes I agree with all of this. We should handle `unknown` flags gracefully, than just saying "nah, we don't understand it". Although that should also be properly defined in the specs too.

> First practical problem; event kinds other than 0,1,2 are not accepted. I think the relay should accept any kind, even those it isn't aware of. This should be an easier fix (adding a "OtherKind" as a catchall for the EventKind enum).

What do you mean by `any kind`? Is it any other kind defined in NIPs? or any random kind that it doesn't know how to read? I don't think its a good idea to allow existence of "random kinds" without their own NIP. Nostr doesn't have DOS protection and at this stage things should be defined strictly via NIPs. Then we can selectively open up to these NIPs and have our compatibility matrix. That way we can ensure that we don't end up with garbage in our DB while being open to the full set of protocol.    

Currently this only supports NIP01. And the next work is to make it compatible with rest of the NIPs.

**Comment by scsibug** [comment]
No plans to merge this one.

**Pull request closed without merging**
