### PR TITLE
Add --help and --version handling

### PR DESCRIPTION
**Pull request by jesterhodl**
Hi, this is my first rust commit. I wanted to address an issue #42 
Is this ok?

### CODE REVIEW

**Comment by schlunsen** [comment]
https://docs.rs/clap/latest/clap/

**Comment by jesterhodl** [comment]
> I would suggest using something like [clap](https://docs.rs/clap/latest/clap/)

I'll check it out, thanks!

**Comment by scsibug** [comment]
This is merged; as noted in the issue, additional improvements in config options or a switch to clap would be great too.  Thanks for your contribution!

**Comment by jesterhodl** [comment]
No worries, I'll work on that, was on a break.

**Pull request closed without merging**
